server:
  port: 8084
  servlet:
    context-path: /product

spring:
  application: product-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dubbomall?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.209.128
    port: 6379
    #    cluster:
    #      nodes: 192.168.209.128:7001,192.168.209.128:7002,192.168.209.129:7001,192.168.209.129:7002,192.168.209.131:7001,192.168.209.131:7002
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  dubbo:
    application:
      name: user-service
    registry:
      address: zookeeper://192.168.209.128:2181
    protocol:
      port: 20884
    provider:
      timeout: 5000
    base-package: distributed.mall.product.service

#  thymeleaf:
#    cache: false
#    check-template: true
#    check-template-location: true
#    enabled: true
#    encoding: UTF-8
#    mode: HTML5
#    prefix: /templates
#    servlet:
#      content-type: text/html
#    suffix: ./html


mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/*.xml




